package org.example;/*
 * This source file was generated by the Gradle 'init' task
 */

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class AppTest {

    @Test
    void testCelsiusToFahrenheitConversion() {
        App app = new App();
        String result = app.convertTemperature("f", 0); // 0°C => 32°F
        assertEquals("32.0", result);
    }

    @Test
    void testFahrenheitToCelsiusConversion() {
        App app = new App();
        String result = app.convertTemperature("c", 212); // 212°F => approx. 99°C
        assertEquals("99.0", result);
    }

    @Test
    void testLowercaseAndUppercaseOptions() {
        App app = new App();
        assertEquals("32.0", app.convertTemperature("F", 0));
        assertEquals("99.0", app.convertTemperature("C", 212));
    }

    @Test
    void testInvalidOption() {
        App app = new App();
        String result = app.convertTemperature("x", 100);
        assertEquals("Invalid option", result);
    }
}
