name: Build
on:
  push:
    branches:
      - main # Asegúrate de que esta sea la rama principal de tu repositorio

jobs:
  DigaOla: # Este job parece llamar a una acción personalizada
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Diga Ola Action # Nombre descriptivo para la acción personalizada
        # Asegúrate de que la acción 'diga-ola-action' exista en .github/actions/diga-ola-action/
        uses: ./.github/actions/diga-ola-action

  Build: # Este es el job que estamos modificando para usar tus nuevas acciones
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4 # Se recomienda usar la versión más reciente (v4 en este caso)
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # ⭐ Llama a tu acción personalizada para configurar los permisos ⭐
      - name: Configure Gradlew Executable Permission
        # Asegúrate de que la acción 'set-gradlew-permission' exista en .github/actions/set-gradlew-permission/
        uses: ./.github/actions/set-gradlew-permission

      # ⭐ Llama a tu acción personalizada para realizar el build ⭐
      - name: Perform Project Build
        # Asegúrate de que la acción 'build-project' exista en .github/actions/build-project/
        uses: ./.github/actions/build-project
